- hosts: all
  become: yes
  vars:
  tasks:
    - name: Install some stuff I like
      ansible.builtin.package:
        name: traceroute 
        state: present

    - name: Install tmux
      ansible.builtin.package:
        name: tmux
        state: present

    - name: Install capackage
      ansible.builtin.package:
        name: ca-certificates
        state: present

    - name: get the lan ca out there
      ansible.builtin.copy:
        src: data/certificates/home.lan.crt
        dest: /usr/local/share/ca-certificates
      notify:
         - update-ca-trust

  handlers:
    - name: update-ca-trust
      shell: update-ca-certificates




