- hosts: nfsserver
  become: yes
  vars:
  tasks:
    - name: Install nfs server packages
      ansible.builtin.package:
        name: nfs-kernel-server
        state: present

    - name: add export
      lineinfile:
        create: no
        dest: /etc/exports
        state: present
        regexp: '^/d'
        line: '/d     192.168.1.0/24(rw,sync,no_subtree_check,no_root_squash)'

    - name: export everything
      shell: exportfs -ar


