- hosts: syslog_server
  become: yes
  vars:
  tasks:
    - name: create log direction
      ansible.builtin.file:
        path: /d/log
        state: directory
        mode: '0755'
        owner: syslog

    - name: enable syslog to listen for remote logs on port 514
      ansible.builtin.copy:
        src: data/70-remote.conf
        dest: /etc/rsyslog.d/70-remote.conf
        validate: rsyslogd -N1 -f %s
      notify:
         - Restart rsyslog

    - name: Start service rsyslog, if not started
      ansible.builtin.service:
       name: rsyslog
       state: started

  handlers:
    - name: Restart rsyslog
      ansible.builtin.service:
        name: rsyslog
        state: restarted

