- hosts: all
  become: yes
  vars:
    sudoers:
      - owenn
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      with_items: "{{ sudoers }}"
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        create: yes
        dest: /etc/sudoers.d/my-escalation
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
 
